/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dent.Int;

import com.dent.clases.ProcesaTabla;
import com.dent.clases.ResumenMySQL;
import java.awt.BorderLayout;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Edwin
 */
public class IntAnaliz extends javax.swing.JFrame {

    /**
//     * Creates new form IntResumen
     */
    ResumenMySQL mysql =new ResumenMySQL();
    DecimalFormat formateador = new DecimalFormat("$ ###,###,###.##");
    
    java.util.Date fecha = new Date();
      
        
        int año =fecha.getYear()+1900;
        int mes =fecha.getMonth()+1;
        int dia =fecha.getDate();
        
        
        
        
        double factu = 0;
        double factuC = 0;
        double factuVT =0;
        double factuTsali = 0;
        double totalFacT= 0;
        double gastoC= 0;
        double compraC= 0;
        double gastoS= 0;
        double compraS= 0;
        
        

    
    
    public IntAnaliz() {
        initComponents();
         año =fecha.getYear()+1900;
         mes =fecha.getMonth()+1;
         dia =fecha.getDate();
         jPanel1.setOpaque(false);
         
         
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1220, 781));
        setResizable(false);
        setSize(new java.awt.Dimension(1220, 781));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtrar por:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel11.setOpaque(false);
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel11.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 90, -1));
        jPanel11.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 80, -1));
        jPanel11.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 80, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel11.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 90, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox4.setSelectedIndex(30);
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel11.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 50, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel11.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 50, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Fecha Final:");
        jPanel11.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 70, 20));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Fecha Inicial:");
        jPanel11.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 20));

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel11.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 117, 50));

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 120));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 1160, 140));

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setDoubleBuffered(true);
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Folio", "Consepto", "Sub Total", "Iva", "Total", "Rfc", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable5);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 460));

        jTabbedPane1.addTab("Producto", jPanel1);

        jPanel3.setOpaque(false);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Folio", "Consepto", "Sub Total", "Iva", "Total", "Rfc", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1465, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Suelto", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 1470, 490));

        jLabel18.setBackground(new java.awt.Color(153, 0, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Resumen de lo mas vendido");
        jLabel18.setOpaque(true);
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dent/imag/red-simple-wallpapers-1920x1080.jpg"))); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(500, 560));
        Fondo.setMinimumSize(new java.awt.Dimension(500, 560));
        Fondo.setRequestFocusEnabled(false);
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-340, -320, 1890, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        
        consulta ();
        Tablas_recarga();
        
        
        
    }//GEN-LAST:event_BuscarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(jSpinner1, "#");
        JSpinner.NumberEditor editor1 = new JSpinner.NumberEditor(jSpinner2, "#");
        jSpinner1.setEditor(editor);
        jSpinner2.setEditor(editor1);
        
        jComboBox1.setSelectedIndex(mes-1);   
        jComboBox3.setSelectedIndex(mes-1); 
        
        jComboBox4.setSelectedIndex(dia-1);   
        jComboBox5.setSelectedIndex(0); 
        
        jSpinner1.setValue(año) ;
        jSpinner2.setValue(año) ;
        
        Tablas_recarga();
        consulta ();
       
        
        System.out.println( dia +" " + mes + " " + año);
        System.out.println(mysql.ConsultaFactu("01","05", "2017","31","05", "2017"));
        

        


    }//GEN-LAST:event_formWindowOpened

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        
        
        
        
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    public void consulta() {
       int año1 = Integer.parseInt(jSpinner1.getValue().toString());

        int año2 = Integer.parseInt(jSpinner2.getValue().toString());

        int mesl = jComboBox1.getSelectedIndex() + 1;
        
        int mes2 = jComboBox3.getSelectedIndex() + 2;
        if (mes2 > 11) {
            mes2 = 1;
            año2 = año2+ 1;

        }
        int dia1 = jComboBox5.getSelectedIndex() + 1;
        int dia2 = jComboBox4.getSelectedIndex() + 1;
        
        String fechain = año1+"/"+mesl+"/"+ dia1;
        
        String fechafin = año2 +"/"+mes2+"/"+dia2;
        System.out.println("De: "+fechain+"  Al: "+fechafin);
        

        String consulta = "CREATE OR REPLACE VIEW sicar.Vventa AS "
                + "select  sum(cantidad)as Vendidos,art_id, DESCRIPCION, avg(precioCompra)as Compra, avg(precioCon)as ventas,(((avg(precioCon)*100)/avg(precioCompra))-100) "
                + "AS UTILIDAD,((avg(precioCon)-avg(precioCompra))*sum(cantidad)) as UtiliMone ,  sum(precioCompra) AS TOTALCOMPRA,  sum(precioCon) AS TOTALVENTA  from sicar.detallev where ven_id IN (select VEN_ID  from sicar.venta\n"
                + "where DATE(fecha)>='"+  fechain+"' AND DATE(fecha)<='"+fechafin+"' AND CAN_CAJ_ID IS NULL ) AND  DESCRIPCION NOT LIKE 'nota%' GROUP BY ART_ID ORDER BY Vendidos desc;";

        mysql.Ejecuta("root", "javac", consulta);

        consulta = "CREATE OR REPLACE VIEW sicar.Vcompras AS "
                + "select com_id, art_id as art_id2, descripcion as descripcion2 , sum(cantidad) as cantidad, sum(importeCon) as venta,avg(precioCon) as PromCom, avg(factor) as factor "
                + "from sicar.detallec  "
                + "where com_id in (select com_id from sicar.compra where  DATE(fecha)>='"+ fechain+"' AND DATE(fecha)<='"+  fechafin+"'AND CAN_CAJ_ID IS NULL )  "
                + "group by art_id ORDER BY  sum(cantidad) desc ;";

        mysql.Ejecuta("root", "javac", consulta);
       
    }
    
    
    public void Tablas_recarga() {
        ProcesaTabla tabla = new ProcesaTabla();

        int año1 = Integer.parseInt(jSpinner1.getValue().toString());

        int año2 = Integer.parseInt(jSpinner2.getValue().toString());

        int mesl = jComboBox1.getSelectedIndex() + 1;
        
        int mes2 = jComboBox3.getSelectedIndex() + 2;
        if (mes2 > 11) {
            mes2 = 1;
            año2 = año2+ 1;

        }

        String consulta = "select * from dentitodo.facturas";

//        DefaultTableModel modelo = tabla.consulta_Tablas(consulta) ;   
//        jTable1.setModel(modelo);
        consulta = "select * from sicar.Vresumen where descripcion not like ('%suelt%')";
        
        DefaultTableModel modelo2 = tabla.consulta_Tablas(consulta);
        jTable5.setModel(modelo2);
        
        consulta = "select * from sicar.Vresumen where descripcion like ('%suelt%') ;";
        
        DefaultTableModel modelo3 = tabla.consulta_Tablas(consulta);
        jTable3.setModel(modelo3);
        
        
        
        
        
        
//        consulta = "SELECT referencia, nombre,rfc ,Fecha_facturada,tipo ,Sub_Total,iva,total,gasto FROM dentitodo.facturas where gasto='Compra' and "
//                + "Fecha_facturada>='" + año1 + "-" + mesl + "-01' and Fecha_facturada<='" + año2 + "-" + mes2 + "-1' and Status=1 order by Fecha_facturada ";
//        DefaultTableModel modelo3 = tabla.consulta_Tablas(consulta);
//        System.out.println(consulta);
//
//        jTable1.setModel(modelo3);

    }

    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(IntResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(IntResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(IntResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(IntResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new IntAnaliz().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable5;
    // End of variables declaration//GEN-END:variables

    private String ConvertirObjectToString(Object value) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
