/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dent.Int;

import com.dent.clases.Articulo;
import com.dent.clases.AutoOnline;
import com.dent.clases.ConexionMySQL;
import com.dent.clases.ManipulaArchivos;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Edwin
 */
public class IntOnline extends javax.swing.JFrame {

    /**
     * Creates new form IntOnline
     */
    ManipulaArchivos archi = new ManipulaArchivos();
    AutoOnline auto = new AutoOnline();
    public static ArrayList<Articulo> listaArticuloSicar = new ArrayList();

    public static ArrayList<Articulo> listaSalida = new ArrayList();
    public static ArrayList<Articulo> listaNO = new ArrayList();

    public IntOnline() {

        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void analiArticulos() {
        
        System.out.println(auto.listaOnline.size());
        for (int i = 0; i < auto.listaOnline.size(); i++) {
            int estado = 0;

            for (int j = 0; j < auto.listaVilla.size(); j++) {
                if (auto.listaOnline.get(i).getCodigo().equals(auto.listaVilla.get(j).getCodigo())) {
                    Articulo artiNue = new Articulo(auto.listaOnline.get(i).getCodigo(),
                            auto.listaOnline.get(i).getArticulo(), auto.listaVilla.get(j).getValor(), 1);
                    listaSalida.add(artiNue);
                    estado = 1;
                    j = auto.listaVilla.size();
                }
            }
            if (estado == 0) {
                for (int j = 0; j < listaArticuloSicar.size(); j++) {

                    if (auto.listaOnline.get(i).getCodigo().equals(listaArticuloSicar.get(j).getCodigo())) {
//                        System.out.println("compara "+auto.listaOnline.get(i).getCodigo()+" "+ auto.listaOnline.get(i).getValor()+"       "+listaArticuloSicar.get(j).getCodigo()+"    "+listaArticuloSicar.get(j).getValor());
                        Articulo artiNue = new Articulo(auto.listaOnline.get(i).getCodigo(), auto.listaOnline.get(i).getArticulo(), listaArticuloSicar.get(j).getValor(), 1);
                        listaSalida.add(artiNue);
                        estado = 1;
                        j = listaArticuloSicar.size();
                    }
                }
            }
            if (estado == 0) {
                Articulo artiNue = new Articulo(auto.listaOnline.get(i).getCodigo(),
                        auto.listaOnline.get(i).getArticulo(), auto.listaOnline.get(i).getValor(), 1);
                listaNO.add(artiNue);
            }
        }
    }
    
    public String ConsolSalida() {
        String aux = "";

        for (int i = 0; i < listaSalida.size(); i++) {
            aux = aux + listaSalida.get(i).getCodigo() + "\t" + listaSalida.get(i).getArticulo() + "\t" + listaSalida.get(i).getValor() + "\n";
        }

        return aux;
    }

    public String ConsolNoSalida() {
        String aux = "";

        for (int i = 0; i < listaNO.size(); i++) {
            aux = aux + listaNO.get(i).getCodigo() + "\t" + listaNO.get(i).getArticulo() + "\t" + listaNO.get(i).getValor() + "\n";
        }
        
        return aux;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ventanaSalida = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        entradaVilla = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ventanaVilla = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        estadoVilla = new javax.swing.JLabel();
        estadoOnline = new javax.swing.JLabel();
        estadoSicar = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ventanaOline = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ventanaSalidaNo = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Online");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        ventanaSalida.setColumns(20);
        ventanaSalida.setRows(5);
        jScrollPane1.setViewportView(ventanaSalida);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dent/iconos/Consultas.fw.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dent/iconos/Consultas.s.fw.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Archivo online");

        entradaVilla.setColumns(20);
        entradaVilla.setRows(5);
        jScrollPane2.setViewportView(entradaVilla);

        ventanaVilla.setBackground(new java.awt.Color(226, 226, 226));
        ventanaVilla.setColumns(20);
        ventanaVilla.setRows(5);
        jScrollPane3.setViewportView(ventanaVilla);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Archivo Villa ");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dent/iconos/icon-.fw.png"))); // NOI18N
        jButton2.setToolTipText("");
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dent/iconos/icon-.fw2.fw.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dent/iconos/Actu.fw.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dent/iconos/Actu2.fw.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado de los Archivos", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        estadoVilla.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        estadoVilla.setText("Datos Villa");

        estadoOnline.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        estadoOnline.setText("Datos Online");

        estadoSicar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        estadoSicar.setText("Datos Sicar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(estadoSicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estadoVilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estadoOnline, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(estadoSicar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(estadoVilla)
                .addGap(14, 14, 14)
                .addComponent(estadoOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ventanaOline.setBackground(new java.awt.Color(226, 226, 226));
        ventanaOline.setColumns(20);
        ventanaOline.setRows(5);
        jScrollPane4.setViewportView(ventanaOline);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Archivo de Salida");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Archivo Villa ");

        ventanaSalidaNo.setColumns(20);
        ventanaSalidaNo.setForeground(new java.awt.Color(153, 153, 255));
        ventanaSalidaNo.setRows(5);
        jScrollPane5.setViewportView(ventanaSalidaNo);

        jMenu1.setText("Opciones");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Guardar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3))
                                    .addGap(36, 36, 36)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        auto.listaOnline.clear();
        auto.online.clear();
        String ruta = archi.ArchivoCadenaCSV(archi.RutaArchivoCSV("csv"));
        auto.ProseOnline(ruta);
        estadoOnline.setText("Datos Online ...... OK");
        estadoOnline.setForeground(Color.green);

        System.out.println("");
        System.out.println("Online");
        System.out.println("");

        System.out.println("Total " + auto.ConvierteArtiOnline());

        for (int i = 0; i < auto.listaOnline.size(); i++) {

            System.out.println(auto.listaOnline.get(i).getArticulo() + "\t" + auto.listaOnline.get(i).getValor());
        }

        ventanaOline.setText(auto.Resulta(1));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        auto.listaVilla.clear();
        auto.villa.clear();
        auto.ProseVilla(entradaVilla.getText());
        System.out.println("");
        System.out.println("Villa");
        System.out.println("");
        System.out.println("Total " + auto.ConvierteArtiVilla());

        ventanaVilla.setText(auto.Resulta(0));
        if (auto.listaVilla.size() != 0) {
            estadoVilla.setText("Datos Villa ....... OK");
            estadoVilla.setForeground(Color.green);

        }
//        for (int i = 0; i < auto.listaVilla.size(); i++) {
//            System.out.println(auto.listaVilla.get(i).getArticulo() + "\t" + auto.listaVilla.get(i).getValor());
//        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        analiArticulos();
        ventanaSalida.setText(ConsolSalida());
        ventanaSalidaNo.setText(ConsolNoSalida());

//        auto.listaOnline.

    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (auto.listaVilla.isEmpty()) {
//            estadoVilla.setText("Datos Villa ....... OK");
//            estadoVilla.setForeground(Color.green);
            estadoVilla.setText("No hay archivos de Villa");
            estadoVilla.setForeground(Color.red);

        }
        if (auto.listaOnline.isEmpty()) {
            estadoOnline.setText("No hay archivos Online");
            estadoOnline.setForeground(Color.red);
//            estadoOnline.setText("Datos Online ...... OK");
//            estadoOnline.setForeground(Color.green);
        }
        ConexionMySQL NN = new ConexionMySQL();
        listaArticuloSicar = NN.ConsultaArticulos();

        if (!listaArticuloSicar.isEmpty()) {
            estadoSicar.setText("Datos Sicar ....... OK");
            estadoSicar.setForeground(Color.green);

        } else {
            estadoSicar.setText("No hay archivos Sicar");
            estadoSicar.setForeground(Color.red);
        }


    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        if (auto.guardaArchivNO() == false || auto.guardaArchivOnline() == false) {
            JOptionPane.showMessageDialog(rootPane, "Error, al guardar Archivos", "Error", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(IntOnline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(IntOnline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(IntOnline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(IntOnline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new IntOnline().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea entradaVilla;
    private javax.swing.JLabel estadoOnline;
    private javax.swing.JLabel estadoSicar;
    private javax.swing.JLabel estadoVilla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea ventanaOline;
    private javax.swing.JTextArea ventanaSalida;
    private javax.swing.JTextArea ventanaSalidaNo;
    private javax.swing.JTextArea ventanaVilla;
    // End of variables declaration//GEN-END:variables
}
