/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dent.Int;

import com.dent.clases.ProcesaTabla;
import com.dent.clases.ResumenMySQL;
import java.awt.BorderLayout;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Edwin
 */
public class IntResumen extends javax.swing.JFrame {

    /**
//     * Creates new form IntResumen
     */
    ResumenMySQL mysql =new ResumenMySQL();
    DecimalFormat formateador = new DecimalFormat("$ ###,###,###.##");
    
    java.util.Date fecha = new Date();
      
        
        int año =fecha.getYear()+1900;
        int mes =fecha.getMonth()+1;
        int dia =fecha.getDate();
        
        
        
        
        double factu = 0;
        double factuC = 0;
        double factuVT =0;
        double factuTsali = 0;
        double totalFacT= 0;
        double gastoC= 0;
        double compraC= 0;
        double gastoS= 0;
        double compraS= 0;
        
        

    
    
    public IntResumen() {
        initComponents();
         año =fecha.getYear()+1900;
         mes =fecha.getMonth()+1;
         dia =fecha.getDate();
         jPanel1.setOpaque(false);
         
         
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gasto_SF = new javax.swing.JLabel();
        compra_SF = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        totalSumaS = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        gasto_Fa = new javax.swing.JLabel();
        compra_Fa = new javax.swing.JLabel();
        compra_Fa1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ventas_TC = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        entrada_Fac = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        totalFac = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        entrada_Fac_C = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        grafica1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        grafica = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1220, 781));
        setPreferredSize(new java.awt.Dimension(1220, 781));
        setResizable(false);
        setSize(new java.awt.Dimension(1220, 781));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtrar por:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel11.setOpaque(false);
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dentitodo", "Odontologia" }));
        jPanel11.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 150, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel11.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 90, -1));
        jPanel11.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 80, -1));
        jPanel11.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 80, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel11.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 90, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox4.setSelectedIndex(30);
        jPanel11.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 50, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel11.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 50, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Fecha Final:");
        jPanel11.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 70, 20));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Fecha Inicial:");
        jPanel11.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 70, 20));

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 770, 140));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 117, 37));

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 60, 117, 38));

        jButton3.setText("jButton3");
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 1160, 140));

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setDoubleBuffered(true);
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Diferencia por Facturar:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(370, 300, 184, 22);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ganancias");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 300, 87, 17);
        jLabel6.getAccessibleContext().setAccessibleName("Total de Facturado:");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pagos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setOpaque(false);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total de Gastos:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total de Compras:");

        gasto_SF.setBackground(new java.awt.Color(255, 255, 255));
        gasto_SF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gasto_SF.setForeground(new java.awt.Color(255, 255, 255));
        gasto_SF.setText("0.0");

        compra_SF.setBackground(new java.awt.Color(255, 255, 255));
        compra_SF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        compra_SF.setForeground(new java.awt.Color(255, 255, 255));
        compra_SF.setText("0.0");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Total de Salidas Sicar:");

        totalSumaS.setBackground(new java.awt.Color(255, 255, 255));
        totalSumaS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalSumaS.setForeground(new java.awt.Color(255, 255, 255));
        totalSumaS.setText("0.0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gasto_SF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalSumaS, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(compra_SF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(gasto_SF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(compra_SF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(totalSumaS))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 36, 320, 133);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Compras Facturadas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setOpaque(false);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total de Gastos:");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total de Compras:");

        gasto_Fa.setBackground(new java.awt.Color(255, 255, 255));
        gasto_Fa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gasto_Fa.setForeground(new java.awt.Color(255, 255, 255));
        gasto_Fa.setText("0.0");

        compra_Fa.setBackground(new java.awt.Color(255, 255, 255));
        compra_Fa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        compra_Fa.setForeground(new java.awt.Color(255, 255, 255));
        compra_Fa.setText("0.0");

        compra_Fa1.setBackground(new java.awt.Color(255, 255, 255));
        compra_Fa1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        compra_Fa1.setForeground(new java.awt.Color(255, 255, 255));
        compra_Fa1.setText("0.0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gasto_Fa, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(compra_Fa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(compra_Fa1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(gasto_Fa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(compra_Fa))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(compra_Fa1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(359, 36, 380, 133);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ventas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel7.setOpaque(false);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total de Ventas:");

        ventas_TC.setBackground(new java.awt.Color(255, 255, 255));
        ventas_TC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ventas_TC.setForeground(new java.awt.Color(255, 255, 255));
        ventas_TC.setText("0.0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(ventas_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ventas_TC))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(10, 187, 320, 80);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ventas Facturadas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.setOpaque(false);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total de Ventas:");

        entrada_Fac.setBackground(new java.awt.Color(255, 255, 255));
        entrada_Fac.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entrada_Fac.setForeground(new java.awt.Color(255, 255, 255));
        entrada_Fac.setText("0.0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(entrada_Fac, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(entrada_Fac))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(359, 187, 380, 80);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("0.0");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(280, 300, 20, 17);

        totalFac.setBackground(new java.awt.Color(255, 255, 255));
        totalFac.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalFac.setForeground(new java.awt.Color(255, 255, 255));
        totalFac.setText("0.0");
        jPanel1.add(totalFac);
        totalFac.setBounds(590, 300, 140, 22);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Facturadas Sicar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel10.setOpaque(false);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Facturas Canceladas");

        entrada_Fac_C.setBackground(new java.awt.Color(255, 255, 255));
        entrada_Fac_C.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        entrada_Fac_C.setForeground(new java.awt.Color(255, 255, 255));
        entrada_Fac_C.setText("0.0");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(entrada_Fac_C, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(entrada_Fac_C))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel10);
        jPanel10.setBounds(790, 190, 270, 73);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoria con mas gastos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel9.setOpaque(false);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Categoria:");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Tipo de Pagos:");

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Proveedor");

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("0.0");

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Tipo de Pagos:");

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("0.0");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(jLabel22))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel27))))
                .addGap(22, 22, 22))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9);
        jPanel9.setBounds(790, 40, 270, 133);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nota: Las salidas de dinero de la caja por parte de Sicar. No se ven reflejadas, hasta realizar el corte de caja.");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(463, 434, 652, 17);

        jTabbedPane1.addTab("Resumen Dentitodo", jPanel1);

        jPanel3.setOpaque(false);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Folio", "Consepto", "Sub Total", "Iva", "Total", "Rfc", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Gastos del mes", jPanel3);

        jPanel2.setOpaque(false);
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Folio", "Consepto", "Sub Total", "Iva", "Total", "Rfc", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1105, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Compras del mes", jPanel2);

        grafica1.setOpaque(false);
        grafica1.setLayout(new java.awt.BorderLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Folio", "Consepto", "Sub Total", "Iva", "Total", "Rfc", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        grafica1.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Grafica", grafica1);

        grafica.setOpaque(false);
        grafica.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("Grafica", grafica);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 1130, 490));

        jLabel18.setBackground(new java.awt.Color(51, 102, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Insertar Gasto");
        jLabel18.setOpaque(true);
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dent/imag/red-simple-wallpapers-1920x1080.jpg"))); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(500, 560));
        Fondo.setMinimumSize(new java.awt.Dimension(500, 560));
        Fondo.setRequestFocusEnabled(false);
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-660, -40, 1950, 1160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        int v1 =300;
        int v2 =300;
        int v3 =300;
        int v4 =300;
        
        DefaultCategoryDataset dataset4 =new DefaultCategoryDataset();

        dataset4.setValue(v1, "", " staric_1");
        dataset4.setValue(v2, "", " staric_2");
        dataset4.setValue(v3, "", " staric_3");
        dataset4.setValue(v4, "", " staric_4");

        JFreeChart chart =  ChartFactory.createBarChart("", null, null, dataset4);
        CategoryPlot catPot =  chart.getCategoryPlot();
        catPot.setRangeGridlinePaint(Color.BLUE);

        ChartPanel chartPanel = new ChartPanel(chart);
        grafica.removeAll();
        grafica.add(chartPanel  , BorderLayout.CENTER);
//        grafica.validate();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Tablas_recarga();
        consulta ();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(jSpinner1, "#");
        JSpinner.NumberEditor editor1 = new JSpinner.NumberEditor(jSpinner2, "#");
        jSpinner1.setEditor(editor);
        jSpinner2.setEditor(editor1);
        
        jComboBox1.setSelectedIndex(mes-1);   
        jComboBox3.setSelectedIndex(mes-1); 
        
        jComboBox4.setSelectedIndex(dia-1);   
        jComboBox5.setSelectedIndex(0); 
        
        jSpinner1.setValue(año) ;
        jSpinner2.setValue(año) ;
        
        Tablas_recarga();
        consulta ();
       
        
        System.out.println(" " + mes + " " + año);
        System.out.println(mysql.ConsultaFactu("01","05", "2017","31","05", "2017"));
        

        


    }//GEN-LAST:event_formWindowOpened

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        
        
        
        
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    
        
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseEntered

    public void consulta (){
        
         factu = mysql.ConsultaFactu(String.valueOf(jComboBox5.getSelectedIndex()+1), String.valueOf(jComboBox1.getSelectedIndex()+1), 
                 String.valueOf(jSpinner1.getValue()),String.valueOf(jComboBox4.getSelectedIndex()+1),String.valueOf(jComboBox3.getSelectedIndex()+1),String.valueOf(jSpinner2.getValue()));
         
         factuC = mysql.ConsultaFactuC(String.valueOf(jComboBox5.getSelectedIndex()+1), String.valueOf(jComboBox1.getSelectedIndex()+1), 
                 String.valueOf(jSpinner1.getValue()),String.valueOf(jComboBox4.getSelectedIndex()+1),String.valueOf(jComboBox3.getSelectedIndex()+1),String.valueOf(jSpinner2.getValue()));
                  
         factuVT = mysql.ConsultaVT(String.valueOf(jComboBox5.getSelectedIndex()+1), String.valueOf(jComboBox1.getSelectedIndex()+1), 
                 String.valueOf(jSpinner1.getValue()),String.valueOf(jComboBox4.getSelectedIndex()+1),String.valueOf(jComboBox3.getSelectedIndex()+1),String.valueOf(jSpinner2.getValue()));
         
         factuTsali = mysql.ConsultaTotalSalidasSicar(String.valueOf(jComboBox5.getSelectedIndex()+1), String.valueOf(jComboBox1.getSelectedIndex()+1), 
                 String.valueOf(jSpinner1.getValue()),String.valueOf(jComboBox4.getSelectedIndex()+1),String.valueOf(jComboBox3.getSelectedIndex()+1),String.valueOf(jSpinner2.getValue()));
         
         gastoC = mysql.ConsultaGasto(String.valueOf(jComboBox5.getSelectedIndex()+1), String.valueOf(jComboBox1.getSelectedIndex()+1), 
                 String.valueOf(jSpinner1.getValue()),String.valueOf(jComboBox4.getSelectedIndex()+1),String.valueOf(jComboBox3.getSelectedIndex()+1),String.valueOf(jSpinner2.getValue()),false);
         compraC = mysql.ConsultaCompra(String.valueOf(jComboBox5.getSelectedIndex()+1), String.valueOf(jComboBox1.getSelectedIndex()+1), 
                 String.valueOf(jSpinner1.getValue()),String.valueOf(jComboBox4.getSelectedIndex()+1),String.valueOf(jComboBox3.getSelectedIndex()+1),String.valueOf(jSpinner2.getValue()),false);
         gastoS = mysql.ConsultaGasto(String.valueOf(jComboBox5.getSelectedIndex()+1), String.valueOf(jComboBox1.getSelectedIndex()+1), 
                 String.valueOf(jSpinner1.getValue()),String.valueOf(jComboBox4.getSelectedIndex()+1),String.valueOf(jComboBox3.getSelectedIndex()+1),String.valueOf(jSpinner2.getValue()),true);
         compraS = mysql.ConsultaCompra(String.valueOf(jComboBox5.getSelectedIndex()+1), String.valueOf(jComboBox1.getSelectedIndex()+1), 
                 String.valueOf(jSpinner1.getValue()),String.valueOf(jComboBox4.getSelectedIndex()+1),String.valueOf(jComboBox3.getSelectedIndex()+1),String.valueOf(jSpinner2.getValue()),true);
         
         
         totalFacT= factu-gastoC-compraC;
         
//         compra_Fa1.setText(String.valueOf(formateador.format(gastoC+compraC)));
         gasto_SF.setText(String.valueOf(formateador.format(gastoS)));
         compra_SF.setText(String.valueOf(formateador.format(compraS)));
         
//         compra_SF
//                 gasto_SF
//                 
//                 compra_Fa1
                 
        entrada_Fac.setText(String.valueOf(formateador.format(factu)));
        entrada_Fac_C.setText(String.valueOf(formateador.format(factuC)));
        ventas_TC.setText(String.valueOf(formateador.format(factuVT)));
        totalSumaS.setText(String.valueOf(formateador.format(factuTsali)));
        
        totalFac.setText(String.valueOf(formateador.format(totalFacT)));
        gasto_Fa.setText(String.valueOf(formateador.format(gastoC)));
        compra_Fa.setText(String.valueOf(formateador.format(compraC)));
        
        
        compra_Fa1.setText(String.valueOf(formateador.format(compraC+gastoC)));
    }
    
    
    public void Tablas_recarga() {
        ProcesaTabla tabla = new ProcesaTabla();

        int año1 = Integer.parseInt(jSpinner1.getValue().toString());

        int año2 = Integer.parseInt(jSpinner2.getValue().toString());

        int mesl = jComboBox1.getSelectedIndex() + 1;
        
        int mes2 = jComboBox3.getSelectedIndex() + 2;
        if (mes2 > 11) {
            mes2 = 1;
            año2 = año2+ 1;

        }

        String consulta = "select * from dentitodo.facturas";

//        DefaultTableModel modelo = tabla.consulta_Tablas(consulta) ;   
//        jTable1.setModel(modelo);
        consulta = "SELECT referencia, nombre,rfc ,Fecha_facturada,tipo ,Sub_Total,iva,total,gasto FROM dentitodo.facturas where gasto='Gasto' and Fecha_facturada>='"
                + año1 + "-" + mesl
                + "-01' and Fecha_facturada<='" + año2 + "-" + mes2+ "-1' and Status=1 order by Fecha_facturada ";

        System.out.println("hola" + (mes2 + 1));
        DefaultTableModel modelo2 = tabla.consulta_Tablas(consulta);
        jTable3.setModel(modelo2);
        System.out.println(consulta);
        
        
        consulta = "SELECT referencia, nombre,rfc ,Fecha_facturada,tipo ,Sub_Total,iva,total,gasto FROM dentitodo.facturas where gasto='Compra' and "
                + "Fecha_facturada>='" + año1 + "-" + mesl + "-01' and Fecha_facturada<='" + año2 + "-" + mes2 + "-1' and Status=1 order by Fecha_facturada ";
        DefaultTableModel modelo3 = tabla.consulta_Tablas(consulta);
        System.out.println(consulta);

        jTable1.setModel(modelo3);

    }

    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(IntResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(IntResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(IntResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(IntResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new IntResumen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel compra_Fa;
    private javax.swing.JLabel compra_Fa1;
    private javax.swing.JLabel compra_SF;
    private javax.swing.JLabel entrada_Fac;
    private javax.swing.JLabel entrada_Fac_C;
    private javax.swing.JLabel gasto_Fa;
    private javax.swing.JLabel gasto_SF;
    private javax.swing.JPanel grafica;
    private javax.swing.JPanel grafica1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel totalFac;
    private javax.swing.JLabel totalSumaS;
    private javax.swing.JLabel ventas_TC;
    // End of variables declaration//GEN-END:variables

    private String ConvertirObjectToString(Object value) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
